{
 "title": "TpLink Power Usage",
 "description": "Visualize TP-Link Smart Plug Metrics",
 "tags": [
  "prometheus",
  "tplink"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "power_cost", "label": "Cost/kWh(£)", "query": "0.2338" },
   { "name": "jobs", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(tplink_online)" }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"tplink-powerstats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device with Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(tplink_relay_state==1)" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 10, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "tplink_relay_state", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Current Power ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tplink_power_load)" }
   ]
  },
  {
   "title": "Energy/Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(tplink_power_today[24h]))",
     "legendFormat": "Max Power"
    }
   ]
  },
  {
   "title": "Cost/Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(tplink_power_today[24h])) * $power_cost",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Estimated Energy 1y",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(tplink_power_today[24h])) * 365"
    }
   ]
  },
  {
   "title": "Watts/hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(tplink_power_load[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(max_over_time(tplink_power_today[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Power Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "tplink_power_load", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max by(alias) (max_over_time(tplink_power_today[24h]))"
    },
    {
     "expr": "max by(alias) (max_over_time(tplink_power_month[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "targets": [
    { "expr": "tplink_voltage", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "tplink_current", "legendFormat": "{{alias}}" },
    { "expr": "kasa_current", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 23 },
   "targets": [
    { "expr": "tplink_rssi", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Office ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "tplink_power_load{alias=~\"3D Printer|AC|Computer|extractor1|extractor2|Mikrotik|Server\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Home",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "tplink_power_load{alias=~\"FW|Stereo|Tado|TV\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "tplink_power_load{alias=~\"Fridge|Kettle\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "High Power Loads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "tplink_power_load{alias=~\"AC|Computer|Server|TV\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Low Power Loads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "tplink_power_load{alias!~\"AC|Computer|Kettle|Server|TV\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}