name: Build & Publish Docker Image

on:
  push:

env:
  APP: ${{ secrets.DOCKERHUB_USERNAME }}/tplink-powerstats
  TEST_TAG: ${{ github.ref_name }}.${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.APP }}:${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -e --rm --env TPLINK_STARTUP_TEST="true" ${{ env.APP }}:${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.APP }}:latest
